<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>e89ff137-c820-4046-8160-613dcafd38b3</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="Views\Client\ClientLogin.cshtml" />
		<Content Remove="Views\Client\ClientRegister.cshtml" />
		<Content Remove="wwwroot\models\smart_hiring_model.pkl" />
	</ItemGroup>

	<ItemGroup>
		<None Include="wwwroot\models\smart_hiring_model.pkl" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DotNetEnv" Version="3.0.0" />
		<PackageReference Include="Google.Cloud.Vision.V1" Version="3.7.0" />
		<PackageReference Include="Microsoft.ML" Version="4.0.2" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
		<PackageReference Include="PuppeteerSharp" Version="13.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.6">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
		<PackageReference Include="pythonnet" Version="3.0.5" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.6" />
		<PackageReference Include="QRCoder" Version="1.6.0" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="8.0.0" />
		<PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="8.0.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
		<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
		<PackageReference Include="System.Threading.RateLimiting" Version="9.0.9" />

	</ItemGroup>

	<ItemGroup>
		<Content Update="wwwroot\models\feature_columns.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>

</Project>